### ISSUE TITLE
v.3.0.42: can't open in OS X 10.7.5

### ISSUE THREAD

**Issue by thoolb** [nodebox/nodebox#402]
I downloaded the recent Nodebox version 3.0.42. 

A.) When I open the app I get an OS X message window about the crashing app. 
Some text lines from the protocoll:
"Process:         launchd [309]
Path:            /Applications/NodeBox_3042.app/Contents/MacOS/NodeBox
Identifier:      be.emrg.nodebox
Version:         ??? (???)
Code Type:       X86-64 (Native)
Parent Process:  launchd [166]
Crashed Thread:  Unknown
Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_INVALID_ADDRESS at 0x00007fff5fc01028
Backtrace not available"

B.) When I try to update Nodebox from v. 3.0.39 via "Help > Check for Udates ..." I get a message window with the following title text:
"java.lang.RuntimeException: javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: No subject alternative DNS name matching secure.nodebox.net found."

• OS X 10.7.5  •  Java 8 Uodate 31 (Build 1.8.0_31-b15)

Any hints to avoid the crash?
Thank you, thomas

**Comment by thoolb** [comment]
I just found and tried this NodeBox version: https://secure.nodebox.net/downloads/NodeBox-3.0.43-rc1.zip

Unfortunately with same result as before. Also a test as another fresh user did not pevent this issue and made the app crash while starting with the mentioned OS X error message window.

**Comment by fdb** [comment]
Hmm, that's not a lot of information to go on.

Here are some things I'm thinking of:

1. We now bundle our own version of Java (1.8.0 update 35), which might conflict with the version you have installed. You could try upgrading to the '35 release and see if that helps, or remove Java entirely if that's an option.

Officially we can't support OS X 10.7 anymore; we try to support the current version and one below, so that's 10.9 and 10.10. We just don't have the resources to support more versions than this.

If you're savvy with the command line you could try running it from there to see if that helps:

1. Open Terminal.app
2. Type /Applications/NodeBox_3042.app/Contents/MacOS/NodeBox
3. press ENTER

----------
The SSL exception is also because we recently switched our sites to SSL and older versions of Java can't handle multiple sites on SSL (they don't support Server Name Indication – SNI).

**Comment by thoolb** [comment]
The Terminal.app output:
" mbp1:~ thomaso$ /Applications/NodeBox_3042.app/Contents/MacOS/NodeBox
Illegal instruction: 4 "
I also tried with "sudo" but with no terminal result after my password.

Also with OS X security setting allowed to open apps from any source I get the mentioned results. 

A deinstallation of Java had no result, the topics' issue remains occuring.

It seems to be  matter of OS X version: 
On an older MacBookPro but with OSX 10.8 the NodeBox v. 3.0.42 does work. 
So I'll keep v. 3.0.39 until I upgrade the OS X.

**Comment by fdb** [comment]
> It seems to be matter of OS X version

Right, that's what I expected. We didn't have any reported issues with users running 10.8-10.10. Thanks for testing anyway and sorry for the inconvenience.

**Comment by fdb** [comment]
I've added a note on the website (nodebox/nodebox.net@de42fd4800eb679e8db830fc17013a6fcfd27b4e).
